version: "3.9"  # optional since v1.27.0
services:
  node-1:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8081:80"
    env_file:
      - dfaasagent.env
    environment:
      AGENT_LISTEN: /ip4/172.16.238.10/tcp/6000
      AGENT_HAPROXY_HOST: 172.16.238.10
    runtime: sysbox-runc
    volumes:
      - ./dfaasagent.env:/agent/dfaasagent.env
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.10
  node-2:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8082:80"
    env_file:
      - dfaasagent.env
    environment:
      AGENT_LISTEN: /ip4/172.16.238.11/tcp/6000
      AGENT_HAPROXY_HOST: 172.16.238.11
    runtime: sysbox-runc
    volumes:
      - ./dfaasagent.env:/agent/dfaasagent.env
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.11
  node-3:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8083:80"
    env_file:
      - dfaasagent.env
    environment:
      AGENT_LISTEN: /ip4/172.16.238.12/tcp/6000
      AGENT_HAPROXY_HOST: 172.16.238.12
    runtime: sysbox-runc
    volumes:
      - ./dfaasagent.env:/agent/dfaasagent.env
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.12

networks:
  p2p-overlay:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"