version: "3.9"  # optional since v1.27.0
services:
  node-1:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8081:80"
    environment:
      AGENT_IPV4: 172.16.238.1
    runtime: sysbox-runc
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.1
  node-2:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8082:80"
    environment:
      AGENT_IPV4: 172.16.238.2
    runtime: sysbox-runc
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.2

  node-3:
    image: dfaas-node:latest
    build:
      context: ./docker
      dockerfile: docker/dfaas-node.dockerfile
    ports:
      - "8083:80"
    environment:
      AGENT_IPV4: 172.16.238.3
    runtime: sysbox-runc
    networks:
      p2p-overlay:
        ipv4_address: 172.16.238.3

networks:
  p2p-overlay:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"