image:
  name: cavecal/scaphandre
  tag: qemuu

port: 8080

resources:
  limits:
    memory: 75Mi
  requests:
    cpu: 75m
    memory: 50Mi

scaphandre:
  command: prometheus
  args: {vm}
  #extraArgs:
  #  containers: true
  rustBacktrace: 'full'

# Run as root user to get proper permissions
userID: 0
groupID: 0
