---
all:
  hosts:
    dfaasctrl:
      ansible_host: ctrl.dfaas.lvh.me
      ansible_port: 12200
  children:
    faasnodes:
      hosts:
        node01:
          ansible_host: node01.dfaas.lvh.me
          ansible_port: 12201
          dfaas_node_id: 1
        node02:
          ansible_host: node02.dfaas.lvh.me
          ansible_port: 12202
          dfaas_node_id: 2
        node03:
          ansible_host: node03.dfaas.lvh.me
          ansible_port: 12203
          dfaas_node_id: 3
  vars:
    ansible_user: debian
    ansible_ssh_pass: debpass2020
    ansible_become_pass: debpass2020

# Per visualizzare il grafo, con anche le variabili: ansible-inventory -i hosts.yml --graph --vars
