#!/usr/bin/env ansible-playbook
---
- hosts: faasnodes

  vars:
    pip_install_packages:
      - name: docker
    docker_users:
      - debian

  tasks:

    # For running command see: https://github.com/prometheus/node_exporter
    # Using "host" network mode, container share host network stack
    # Node exporter exposes metrics on "localhost:9100"
    # - name: Run container based on node-exporter image
    #   become: yes
    #   docker_container:
    #     name: node-exporter
    #     image: quay.io/prometheus/node-exporter:latest
    #     restart_policy: unless-stopped
    #     network_mode: "host"
    #     pid_mode: "host"
    #     volumes:
    #       - /home/debian/node_exporter:/host:ro,rslave
    #     command: --path.rootfs=/host # Check this for data retention.

    # This task copy on controlled machines prometheus modified config file
    # This file scrape metrics of "node_exporter" from localhost:9100
    - name: Upload prometheus configuration file
      synchronize:
        # Trailing slash required! See http://qdosmsq.dunbar-it.co.uk/blog/2013/02/rsync-to-slash-or-not-to-slash/
        src: "{{playbook_dir}}/exporters-config/prometheus/"
        dest: "/home/debian/exporters-config"
        perms: no # Do not preserve permissions (since we may run this playbook from WSL on Windows, hence permissions are rwx for everyone)
    
    - name: Replace CRLF with LF in prometheus.yml file
      replace:
        path: /home/debian/exporters-config/prometheus.yml
        regexp: '\r\n'
        replace: '\n'

    - name: Upload docker-compose file used for OpenFaaS stack
      synchronize:
        # Trailing slash required! See http://qdosmsq.dunbar-it.co.uk/blog/2013/02/rsync-to-slash-or-not-to-slash/
        src: "{{playbook_dir}}/exporters-config/openfaas-stack-compose/"
        dest: "/home/debian/exporters-config"
        perms: no # Do not preserve permissions (since we may run this playbook from WSL on Windows, hence permissions are rwx for everyone)

    - name: Replace CRLF with LF in docker-compose.yml file of OpenFaaS deploy stack
      replace:
        path: /home/debian/exporters-config/docker-compose.yml
        regexp: '\r\n'
        replace: '\n'

    # This task stop docker stack running on DFaaSNodes. 
    # Change configuration file for prometheus is not possible while running.
    - name: Remove running OpenFaaS stack
      command: docker stack rm func
      ignore_errors: yes
      
    # This task re-run docker compose stack of OpenFaaS.
    - name: Re-run stack based on updated compose file
      command: docker stack deploy func --compose-file /home/debian/exporters-config/docker-compose.yml
